[package]
name = "qemu-launcher"
version = "0.1.0"
authors = ["Garry Filakhtov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12"
proc-mounts = "0.2"
yaml-rust = "0.4.4"
